### ISSUE TITLE
Phaseshift generation fails randomly

### ISSUE THREAD

**Issue by MaxBuchta** [viperleed/viperleed#277]
On this structure, the generation of the phaseshift file fails. When i use the DFT models Poscar, the generation worked normally. 
On other structures i calculated, i could not find this problem. 

[Phaseshift_Tests.zip](https://github.com/user-attachments/files/17844280/Phaseshift_Tests.zip)

**Comment by MaxBuchta** [comment]
Hi Alex, 
no its not physical, i just use it to get the right symmetry. Its not a problem to move them closer. 
Thank you!

**Comment by amimre** [comment]
Ok, great!
I'll mark this issue as resolved, then. Feel free to open it back up or create a new one if this comes up again.
